name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - run: |
          yum install glibc-static
          for py in cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310; do
            /opt/python/${py}/bin/python -m pip install ninja wheel cython
          done
      - run: |
          for py in cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310; do
            /opt/python/${py}/bin/python setup.py bdist_wheel
          done
          