name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v1
      - run: |
          export IVPM_PYTHON=/opt/python/cp37-cp37m/bin/python
          ${IVPM_PYTHON} -m pip install ivpm
          ${IVPM_PYTHON} -m ivpm update -a
      - run: |
          yum install -y glibc-static
          for py in cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310; do
            /opt/python/${py}/bin/python -m pip install ninja wheel cython
          done
      - run: |
          export BUILD_NUM=$GITHUB_RUN_ID
          for py in cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310; do
            /opt/python/${py}/bin/python setup.py bdist_wheel
          done
          